//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceFinder.Data.Impl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonLanguageVo
    {
        public CommonLanguageVo()
        {
            this.Common_Locale = new HashSet<CommonLocaleVo>();
            this.Common_TranslateSizingWord = new HashSet<CommonTranslateSizingWordVo>();
        }
    
        public int LangId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CommonLocaleVo> Common_Locale { get; set; }
        public virtual ICollection<CommonTranslateSizingWordVo> Common_TranslateSizingWord { get; set; }
    }
}
