//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceFinder.Data.Impl.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowConfigurationEntities : DbContext
    {
        public FlowConfigurationEntities()
            : base("name=FlowConfigurationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CommonLanguageVo> Common_Language { get; set; }
        public DbSet<CommonLocaleVo> Common_Locale { get; set; }
        public DbSet<CommonProductFamilyVo> Common_ProductFamily { get; set; }
        public DbSet<CommonProductLineVo> Common_ProductLine { get; set; }
        public DbSet<CommonProductPropertyVo> Common_ProductProperty { get; set; }
        public DbSet<CommonProductPropertyGroupVo> Common_ProductPropertyGroup { get; set; }
        public DbSet<CommonTranslateSizingWordVo> Common_TranslateSizingWord { get; set; }
        public DbSet<CommonTranslateSizingWordIdVo> Common_TranslateSizingWordId { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
